development:
  secret_key: 'sk_test_xDJ5KS0I8VgJvHSQT1Iuxy56'
  publishable_key: 'pk_test_AUn823FKTadliNg29onudWm0'
staging:
  secret_key: 'sk_test_xDJ5KS0I8VgJvHSQT1Iuxy56'
  publishable_key: 'pk_test_AUn823FKTadliNg29onudWm0'
production:
  secret_key: 'sk_live_AeXiNKr9exyKoR0iazUO2sY6'
  publishable_key: 'pk_live_izM2DZiCp32MYwrzjqD4nviT'

